apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
    - image: registry.demodash.com/react/demodash_landing
      context: react
  tagPolicy:
    gitCommit:
  local:
    useBuildkit: true

deploy:
  kubectl:
    manifests:
    - k8s-react/*
