apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
    - image: registry.demodash.com/react/demodash_landing
      context: react
      docker:
        buildArgs:
          REACT_APP_API_HOST: 'https://api.demodash.com'
          REACT_APP_DASHBOARD_HOST: 'https://dashboard.demodash.com'
  tagPolicy:
    gitCommit:
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - k8s-react/*
