apiVersion: apps/v1
kind: Deployment
metadata:
  name: demodash-landing
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demodash-landing
  template:
    metadata:
      labels:
        app: demodash-landing
    spec:
      containers:
        - name: main
          image: registry.demodash.com/react/demodash_landing
          ports:
          - containerPort: 8080
          env:
          - name: REACT_APP_API_HOST
            value: "api.demodash.com"
          - name: REACT_APP_DASHBOARD_HOST
            value: "dash.demodash.com"
